# Use custom format
# [┏━━━━━━━━━━━━━━━━━━┓](bold blue) 
# [┗━━━┛](bold blue) 
format = """
[┏━━━━━━━━━━━━━━━━━━>](bold blue) 
[┃](bold blue)[ ](bold orange)$directory
[┃](bold blue)[ ](bold orange)$git_branch $git_commit $git_state $git_metrics $git_status
[┃](bold blue)[ ](bold orange)$python$sudo$time$status$cmd_duration
[┗━━━>](bold blue) 
"""


# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = true
