#+TITLE: Doom Emacs Config
#+AUTHOR: Matthias Stein
#+DESCRIPTION: This is my living Doom Emacs config.
#+STARTUP: overview

* Intro
When I started with *Doom Emac* it was quite overwhelming. I saw some footage in
YouTube videos that sparkeled my interest, but really starting with *Doom Emacs*
was a steep learning curve - still is, actually.

One thing was the config. You can configure so much, that I soon lost track of
what I did. When I changed something else some weeks later, I wasn't so sure
what all the entries I did previously really did in many cases.

While searching for a way to properly document my config, I stumbled accross
other people using an org file as a combination of documentation and config.
With the options of org mode, it was much easier for me to bring some structure
to my config; much easier than to work with the comment blocks in the initial
/config.el/.

I recently removed most of the stuff which I wasn't so sure what it actually was
about. I added a lot of stuff I read about or saw some YouTube footage about
which looked interesting and soon lost track. Now I start adding stuff when I
actually miss some functionality, a much more sensible apporach :-)

* Personal Information
** Set full name
#+BEGIN_SRC emacs-lisp
(setq user-full-name "Matthias Stein")
#+END_SRC
** Set email address
#+BEGIN_SRC emacs-lisp
(setq user-mail-address "matthias.stein3@gmail.com")
#+END_SRC
* Appearance
** Line Numbers
This determines the style of line numbers in effect. If set to `nil', line f set
to `t' numbers are enabled. For relative line numbers, set this to `relative'.
#+BEGIN_SRC emacs-lisp
(setq display-line-numbers-type 'relative)
#+END_SRC
** Ruler at 80 Characters
To display a ruler at 80 characters, I tried several options, currently I don't
use a rule, but color text on position 81+ in red.
#+BEGIN_SRC emacs-lisp
(require 'whitespace)
(setq whitespace-style '(face empty tabs lines-tail trailing))
(global-whitespace-mode t)
#+END_SRC
** Splash Screen Image
I downloaded some Emacs and Doom images from the webs, then finally created my
own Doom Emacs logo for the splash screen.
+ [[https://commons.wikimedia.org/wiki/File:Emacs-logo.svg][Emacs text svg]]
+ [[https://upload.wikimedia.org/wikipedia/commons/archive/0/08/20170809234614%21EmacsIcon.svg][Emacs logo circle 2010]]
+ [[https://commons.wikimedia.org/wiki/File:EmacsIcon.svg][Emacs logo circle 2017]]
+ [[https://www.deviantart.com/ultravioletbat/art/Yay-Evil-111710573][Yay Evil DeviantArt]]
#+BEGIN_SRC emacs-lisp
;; (setq fancy-splash-image "~/.config/doom/imgs_emacs_logo_text.svg")
;; (setq fancy-splash-image "~/.config/doom/imgs_emacs_logo_2017.svg")

;; Solarized Dark
;; (setq fancy-splash-image "~/.config/doom/imgs/self_doom_emacs_0001.svg")
;; Dracula
(setq fancy-splash-image "~/.config/doom/imgs/self_doom_emacs_0002.svg")
#+END_SRC
** Theme
I like dark themes, currently I can't decide if I like [[https://ethanschoonover.com/solarized/][Solarized]] or [[https://draculatheme.com/][Dracula]] and
continue to swtich between both. Please see above for a matching Splash Screen.
#+BEGIN_SRC emacs-lisp
;; (setq doom-theme 'doom-one)
;; (setq doom-theme 'doom-solarized-dark)
(setq doom-theme 'doom-dracula)
#+END_SRC

